from __future__ import annotations

import importlib.util
import json
import zipfile
from pathlib import Path


ROOT = Path(__file__).resolve().parents[1]
SCRIPT = (
    ROOT
    / "skills"
    / "_runtime"
    / "template-fidelity"
    / "scripts"
    / "validate_docx_text_only.py"
)
SPEC = importlib.util.spec_from_file_location("validate_docx_text_only", SCRIPT)
MODULE = importlib.util.module_from_spec(SPEC)
assert SPEC and SPEC.loader
SPEC.loader.exec_module(MODULE)


CONTENT_TYPES = b"""<?xml version="1.0" encoding="UTF-8"?>
<Types xmlns="http://schemas.openxmlformats.org/package/2006/content-types">
  <Default Extension="xml" ContentType="application/xml"/>
</Types>
"""


def document_xml(text: str, *, color: str = "FF0000", extra_run: bool = False) -> bytes:
    extra = "<w:r><w:t>extra</w:t></w:r>" if extra_run else ""
    return f"""<?xml version="1.0" encoding="UTF-8"?>
<w:document xmlns:w="http://schemas.openxmlformats.org/wordprocessingml/2006/main">
  <w:body><w:tbl><w:tr><w:tc><w:p><w:r><w:rPr><w:rFonts w:eastAsia="宋体"/><w:sz w:val="24"/><w:color w:val="{color}"/></w:rPr><w:t>{text}</w:t></w:r>{extra}</w:p></w:tc></w:tr></w:tbl><w:sectPr/></w:body>
</w:document>
""".encode()


def core_xml(comments: str = "") -> bytes:
    return f"""<?xml version="1.0" encoding="UTF-8"?>
<cp:coreProperties xmlns:cp="http://schemas.openxmlformats.org/package/2006/metadata/core-properties" xmlns:dc="http://purl.org/dc/elements/1.1/"><dc:creator>共创研究院</dc:creator><dc:description>{comments}</dc:description></cp:coreProperties>
""".encode()


def make_docx(
    path: Path,
    *,
    text: str,
    color: str = "FF0000",
    extra_run: bool = False,
    comments: str = "",
    header: bytes = b"<h>fixed letterhead</h>",
) -> None:
    with zipfile.ZipFile(path, "w") as archive:
        archive.writestr("[Content_Types].xml", CONTENT_TYPES)
        archive.writestr("word/document.xml", document_xml(text, color=color, extra_run=extra_run))
        archive.writestr("word/header1.xml", header)
        archive.writestr("docProps/core.xml", core_xml(comments))


def test_text_only_replacement_passes_without_python_docx(tmp_path: Path):
    template = tmp_path / "template.docx"
    output = tmp_path / "output.docx"
    make_docx(template, text="原内容")
    make_docx(output, text="替换后的内容")

    report = MODULE.compare(template, output)

    assert report["status"] == "pass"
    assert report["changed_text_node_count"] == 1
    assert report["visual_review_required"] is True


def test_font_or_color_change_is_rejected(tmp_path: Path):
    template = tmp_path / "template.docx"
    output = tmp_path / "output.docx"
    make_docx(template, text="原内容", color="FF0000")
    make_docx(output, text="替换内容", color="000000")

    report = MODULE.compare(template, output)

    assert report["status"] == "fail"
    assert any("结构或格式变化" in error for error in report["errors"])


def test_added_run_is_rejected(tmp_path: Path):
    template = tmp_path / "template.docx"
    output = tmp_path / "output.docx"
    make_docx(template, text="原内容")
    make_docx(output, text="替换内容", extra_run=True)

    report = MODULE.compare(template, output)

    assert report["status"] == "fail"


def test_header_or_letterhead_change_is_rejected(tmp_path: Path):
    template = tmp_path / "template.docx"
    output = tmp_path / "output.docx"
    make_docx(template, text="原内容")
    make_docx(output, text="替换内容", header=b"<h>changed letterhead</h>")

    report = MODULE.compare(template, output)

    assert report["status"] == "fail"
    assert any("word/header1.xml" in error for error in report["errors"])


def test_python_docx_generator_metadata_is_rejected(tmp_path: Path):
    template = tmp_path / "template.docx"
    output = tmp_path / "output.docx"
    make_docx(template, text="原内容")
    make_docx(output, text="替换内容", comments="generated by python-docx")

    report = MODULE.compare(template, output)

    assert report["status"] == "fail"
    assert any("python-docx" in error for error in report["errors"])


def test_nonvisual_core_metadata_text_may_change(tmp_path: Path):
    template = tmp_path / "template.docx"
    output = tmp_path / "output.docx"
    make_docx(template, text="原内容", comments="模板副本")
    make_docx(output, text="替换内容", comments="共创研究院正式交付")

    report = MODULE.compare(template, output)

    assert report["status"] == "pass"


def test_suite_routes_template_fidelity_contract_to_document_skills():
    manifest = json.loads((ROOT / "skills" / "suite-manifest.json").read_text())
    assert "_runtime/template-fidelity" in manifest["shared_paths"]

    for skill in (
        "application-writing",
        "high-tech-enterprise-application-drafting",
        "standard-drafting",
    ):
        text = (ROOT / "skills" / skill / "SKILL.md").read_text()
        assert "validate_docx_text_only.py" in text
        assert "python-docx" in text
        assert "红字" in text
