#!/usr/bin/env python3
"""Verify that a DOCX changed only existing body text nodes.

This validator intentionally uses only ZIP/XML primitives. It never opens or
rewrites the document through python-docx.
"""

from __future__ import annotations

import argparse
import hashlib
import json
import sys
import zipfile
from pathlib import Path
from xml.etree import ElementTree as ET


W_NS = "http://schemas.openxmlformats.org/wordprocessingml/2006/main"
TEXT_TAG = f"{{{W_NS}}}t"
BODY_PART = "word/document.xml"
CORE_PART = "docProps/core.xml"
GENERATOR_MARKERS = ("python-docx", "generated by python", "generated by python-docx")


def sha256_bytes(data: bytes) -> str:
    return hashlib.sha256(data).hexdigest()


def node_signature(node: ET.Element, *, allow_text: bool) -> tuple:
    text = None if allow_text and node.tag == TEXT_TAG else node.text
    children = tuple(node_signature(child, allow_text=allow_text) for child in list(node))
    return (
        node.tag,
        tuple(sorted(node.attrib.items())),
        text,
        node.tail,
        children,
    )


def structure_signature(node: ET.Element) -> tuple:
    return (
        node.tag,
        tuple(sorted(node.attrib.items())),
        None,
        node.tail,
        tuple(structure_signature(child) for child in list(node)),
    )


def parse_xml(data: bytes, part: str) -> ET.Element:
    try:
        return ET.fromstring(data)
    except ET.ParseError as exc:
        raise ValueError(f"XML解析失败：{part}: {exc}") from exc


def body_texts(root: ET.Element) -> list[str]:
    return [(node.text or "") for node in root.iter(TEXT_TAG)]


def compare(template: Path, output: Path) -> dict:
    errors: list[str] = []
    changed_text_nodes: list[dict[str, object]] = []
    checked_parts = 0

    if template.resolve() == output.resolve():
        errors.append("模板与输出不得是同一文件")

    try:
        template_zip = zipfile.ZipFile(template)
        output_zip = zipfile.ZipFile(output)
    except (FileNotFoundError, zipfile.BadZipFile) as exc:
        return {"status": "fail", "errors": [f"DOCX不可读取：{exc}"]}

    with template_zip, output_zip:
        template_names = set(template_zip.namelist())
        output_names = set(output_zip.namelist())
        if template_names != output_names:
            added = sorted(output_names - template_names)
            removed = sorted(template_names - output_names)
            if added:
                errors.append("输出新增包部件：" + "、".join(added))
            if removed:
                errors.append("输出删除包部件：" + "、".join(removed))

        if BODY_PART not in template_names or BODY_PART not in output_names:
            errors.append(f"缺少正文部件：{BODY_PART}")

        for part in sorted(template_names & output_names):
            template_data = template_zip.read(part)
            output_data = output_zip.read(part)
            checked_parts += 1

            if part == BODY_PART:
                try:
                    template_root = parse_xml(template_data, part)
                    output_root = parse_xml(output_data, part)
                except ValueError as exc:
                    errors.append(str(exc))
                    continue
                if node_signature(template_root, allow_text=True) != node_signature(
                    output_root, allow_text=True
                ):
                    errors.append(
                        "正文存在文字节点之外的结构或格式变化；禁止新增、删除或重排段落、运行、表格、样式及节属性"
                    )
                    continue
                template_texts = body_texts(template_root)
                output_texts = body_texts(output_root)
                if len(template_texts) != len(output_texts):
                    errors.append("正文文字节点数量发生变化")
                    continue
                for index, (before, after) in enumerate(
                    zip(template_texts, output_texts, strict=True), 1
                ):
                    if before != after:
                        changed_text_nodes.append(
                            {
                                "index": index,
                                "before_length": len(before),
                                "after_length": len(after),
                            }
                        )
                continue

            if part == CORE_PART:
                try:
                    template_root = parse_xml(template_data, part)
                    output_root = parse_xml(output_data, part)
                except ValueError as exc:
                    errors.append(str(exc))
                    continue
                if structure_signature(template_root) != structure_signature(output_root):
                    errors.append("核心属性结构发生变化")
                metadata_text = " ".join(node.text or "" for node in output_root.iter()).casefold()
                if any(marker in metadata_text for marker in GENERATOR_MARKERS):
                    errors.append("输出元数据暴露 python-docx 或 Python 重建生成器")
                continue

            if template_data == output_data:
                continue

            if part.endswith(".xml") or part.endswith(".rels") or part == "[Content_Types].xml":
                try:
                    template_root = parse_xml(template_data, part)
                    output_root = parse_xml(output_data, part)
                except ValueError as exc:
                    errors.append(str(exc))
                    continue
                if node_signature(template_root, allow_text=False) != node_signature(
                    output_root, allow_text=False
                ):
                    errors.append(f"受保护部件发生变化：{part}")
            else:
                errors.append(
                    f"受保护二进制部件发生变化：{part} "
                    f"{sha256_bytes(template_data)} -> {sha256_bytes(output_data)}"
                )

    return {
        "schema_version": 1,
        "status": "pass" if not errors else "fail",
        "mode": "docx-existing-text-nodes-only",
        "template": str(template),
        "output": str(output),
        "checked_parts": checked_parts,
        "changed_text_node_count": len(changed_text_nodes),
        "changed_text_nodes": changed_text_nodes,
        "protected_visual_properties": [
            "structure",
            "font",
            "font_size",
            "color",
            "letterhead",
            "headers_footers",
            "table_layout",
            "section_properties",
            "media",
        ],
        "visual_review_required": True,
        "errors": errors,
    }


def main() -> int:
    parser = argparse.ArgumentParser(
        description="校验DOCX仅替换既有正文文字节点，未重建或重排模板"
    )
    parser.add_argument("template", type=Path)
    parser.add_argument("output", type=Path)
    parser.add_argument("--report", type=Path)
    args = parser.parse_args()

    report = compare(args.template, args.output)
    rendered = json.dumps(report, ensure_ascii=False, indent=2)
    if args.report:
        args.report.parent.mkdir(parents=True, exist_ok=True)
        args.report.write_text(rendered + "\n", encoding="utf-8")
    print(rendered)
    return 0 if report["status"] == "pass" else 1


if __name__ == "__main__":
    sys.exit(main())
